development:
  adapter: postgresql
  encoding: unicode
  database: qeba_parking_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: qeba_parking_test
  pool: 5

production:
  pool: 40
